### ISSUE TITLE
Flowers - Behavior

### ISSUE THREAD

**Issue by saporter** [FortWorthGameDev/HeartHome#12]
We need a prefab that behaves in the following way: Once placed in the Scene, it starts off small then blooms to full size and remains that way until killed.

Sprites (in another issue):
1. Small green plant
2. Medium flower
3. Full grown flower 
4. Withered flower (for death)

Sound --> a "success" sound of some sort for the first flower created.  See: https://docs.google.com/document/d/1pR9PLLrS4NxCNCBC2EqR4rsC7BtZ7ym85IjhC7at_sM/edit?ts=5aa946ee#bookmark=id.ulrz9evqnil

Programmer --> Behavior:
-->First created with Small Green Plant, then 5 seconds later turns into Medium Flower, then 5 seconds later turns into Normal Flowers
-->On command, Flowers should turn into a Withered Flower (sprite)
-->When 40th flower is made, the Ghost character (see Ghost issue) should be created and spawned on top of the house: https://docs.google.com/document/d/1pR9PLLrS4NxCNCBC2EqR4rsC7BtZ7ym85IjhC7at_sM/edit?ts=5aa946ee#bookmark=id.k76e97ateg2o

Note: Flowers need to keep track of the order in which they're created (see Ghost, Paintbrush or Hoe/Seeds/WateringCan in doc for why).  Just keep track of this with a static member of some sort

Design doc:
https://docs.google.com/document/d/1pR9PLLrS4NxCNCBC2EqR4rsC7BtZ7ym85IjhC7at_sM/edit?ts=5aa946ee#bookmark=id.peqtc633h0p

**Comment by LanceBailey** [comment]
Created flower prefab, added audio effects for flower growing, small fanfare attached to the flower.
Flower grows in 5 second intervals.
Fanfare should be played only on the first flower.  As of 4/8 it is just attached to the flower prefab.

Remaining issues (ghost interactions, counting flowers) transferred to issue #58
