### ISSUE TITLE
Item - PAINTBRUSH

### ISSUE THREAD

**Issue by saporter** [FortWorthGameDev/HeartHome#19]
Need:
Artist --> Sprite for a Paintbrush (think of it as a kind of mouse icon)
Sound --> A "plopping" Flowers sound?  This is a whimsical sort of action anyway, so enjoy yourself with this one
Programmer --> Once the player has manually created four flowers with HOE, then SEEDS then watering with WATERING CAN, those three items should be eliminated from inventory and replaced with the Paintbrush.  When Paintbrush is selected, the player should be able to paint Flowers (or Small Green Plants anyway) wherever they like with the Mouse.

Notes:
The workflow here is to first use the HOE, SEEDS and WATERING CAN to manually plant flowers x4 before allowing the player to just paint flowers wherever. 

Design Doc:
https://docs.google.com/document/d/1pR9PLLrS4NxCNCBC2EqR4rsC7BtZ7ym85IjhC7at_sM/edit?ts=5aa946ee#bookmark=id.ulrz9evqnil

**Comment by saporter** [comment]
Started this one.  Added Paintbrush (unfinished) prefab and made a script which creates a Flower either in front of the player or with the mouse

**Comment by fregas** [comment]
looks like this is done?

**Comment by LanceBailey** [comment]
I'd say it's done

**Comment by LanceBailey** [comment]
Actually not done there's still audio to be added for the digging/planting.
