### ISSUE TITLE
Wandering Music

### ISSUE THREAD

**Issue by saporter** [FortWorthGameDev/HeartHome#21]
Need background music for when the player is wandering around the map and searching.  First instance used:
https://docs.google.com/document/d/1pR9PLLrS4NxCNCBC2EqR4rsC7BtZ7ym85IjhC7at_sM/edit?ts=5aa946ee#bookmark=id.og07cb2ux0tq

From Mai: "the wandering music should be the same whenever the Girl and her Heart are in the Darkness rather than foreshadowing the home ahead—it could be more reflective and romantic, something that evokes a journey (see Howl’s Moving Castle Theme in the Mood Songs section): https://docs.google.com/document/d/1pR9PLLrS4NxCNCBC2EqR4rsC7BtZ7ym85IjhC7at_sM/edit?ts=5aa946ee#bookmark=id.hetgkr5yrdmk"

**Comment by LanceBailey** [comment]
Created music for "wandering", it is in the assets folder but not yet implemented on any objects in the game.  Will need to be implemented when we get levels working.
