### ISSUE TITLE
Music: Ghost music

### ISSUE THREAD

**Issue by saporter** [FortWorthGameDev/HeartHome#28]
Music needed: Tension music for when Ghost appears

Design Doc:
https://docs.google.com/document/d/1pR9PLLrS4NxCNCBC2EqR4rsC7BtZ7ym85IjhC7at_sM/edit?ts=5aa946ee#bookmark=id.28lx276qka34

**Comment by wingheart** [comment]
something like this when the Ghost first appears, watching the Girl: 
**Colorless Aura:** https://incompetech.com/music/royalty-free/mp3-royaltyfree/Colorless%20Aura.mp3
**Lament of a Stranger:** https://www.youtube.com/watch?v=EQ89IHD75js

- Introduction song that is a bit unsettling, just a tiny but sad, but for the most part leaves the player confused and wondering what is going to happen and what the Ghost's motivation is

**Comment by LanceBailey** [comment]
Oh blast... I didn't notice the reference tracks until I was done!  My idea is a little heavier, especially than Colorless Aura, and perhaps too tense, but I'm happy with it.  See what you think, it can be tweaked no problem!

**Comment by LanceBailey** [comment]
Implemented ghost music

**Comment by saporter** [comment]
@LanceBailey Closed.  We can re-approach the following on #91  (since the flower audio that's drowning out the BGM will presumably go away) --> I think it would add to the tension if we slowly turn down the cottage music when the ghost first appears; then play the ghost music when the ghost first inspects the flower.

You'll notice the updated ghost has a FadeIn parameter for that dictates how long it takes for the ghost to start appearing.  Then a separate coroutine for it's "curious" inspection of the flowers and subsequent killing spree.  I wrote it that way to leave you room to play with the audio in the same way I play with the sprite alpha.  Something to consider.

**Comment by saporter** [comment]
@LanceBailey meant #91
