### ISSUE TITLE
Girls actions

### ISSUE THREAD

**Issue by ldavila07** [FortWorthGameDev/HeartHome#5]
Need PlayerController scripts for:
 -WASD movement (link in with animation once complete)
-SPACE for action.  Two ways to use- 
-- 1. Should be able to detect "actionable" items in front of character and perform a generic action w space.  Generally, this action will be to pick up an item and add it to the inventory.  Design some convention for this and let the team know how to implement future items.
-- 2. If not next to an "actionable" item, then a selected item in inventory will be used ("use" should be defined by each individual item).  Design some convention for this and let the team know how to implement future items. 
(Dependency: Inventory system... or implement a clever way of decoupling this)

-Mouse should be able to invoke action at click area.  Same as SPACE but without the requirement that the Player be standing next to the item

Design doc:
https://docs.google.com/document/d/1pR9PLLrS4NxCNCBC2EqR4rsC7BtZ7ym85IjhC7at_sM/edit?ts=5aa946ee#bookmark=id.htss3ghay33k

**Comment by saporter** [comment]
Still need to add mouse functionality
