### ISSUE TITLE
Girl Design (sprites)

### ISSUE THREAD

**Issue by ldavila07** [FortWorthGameDev/HeartHome#6]
Sprites needed:
-For girl up, down and side (3 for each for animation)
-Sprite sheet for girl sitting down (facing camera)
(See: https://docs.google.com/document/d/1pR9PLLrS4NxCNCBC2EqR4rsC7BtZ7ym85IjhC7at_sM/edit?ts=5aa946ee#bookmark=id.7gxc7eb7go6j)

Be aware:  There is a Girl-combines-with-her-Heart animation, then the Girl "glows."  Add whatever art assets we need to accomplish this effect.  See Ending Sequence issue for this.  Also here: https://docs.google.com/document/d/1pR9PLLrS4NxCNCBC2EqR4rsC7BtZ7ym85IjhC7at_sM/edit?ts=5aa946ee#bookmark=id.w2vk6bw2wbs  

Lower priority:
At some point the game, the girl will additionally be wearing:
-Crown, then
-Crown & Cape, then
-Crown & Cape and holding a Scepter
(See: https://docs.google.com/document/d/1pR9PLLrS4NxCNCBC2EqR4rsC7BtZ7ym85IjhC7at_sM/edit?ts=5aa946ee#bookmark=id.fhkuxij0p15k)

Steal something from somewhere to get girl sprites (opengameart.org)
OR
Make them by hand

**Comment by saporter** [comment]
9 sprite sheets for girl up, down and side 
64x64

**Comment by wingheart** [comment]
![90ff2b29-89cf-4b81-a60e-5a2b964a4a2f](https://user-images.githubusercontent.com/2917868/38492640-7479a840-3ba4-11e8-9a9f-623943009232.png)

Sketch idea for the Girl. The main takeaway is her energy—vivid, whimsical, young. I like the color combinations the most. There’s something fantasy-oriented and imaginary about her and it’s reflected in her environment as well. @saporter

**Comment by saporter** [comment]
Word.  I'll see what we can find (or make).  Hopefully we just get lucky and find something that works on opengameart.org

**Comment by wingheart** [comment]
![girl png](https://user-images.githubusercontent.com/2917868/38629008-aea3f556-3d67-11e8-8e3e-22dba64df0d7.png)
@saporter General look within the limitations of the sprite sheet generator I found (http://gaurav.munjal.us/Universal-LPC-Spritesheet-Character-Generator/)

**Comment by saporter** [comment]
@wingheart I'll add these in, but there's also segments where she wears a cape and a crown.  Does the sprite sheet generator have the ability to create at least two more (one like the above, but wearing a cape, and another one wearing a cape + crown)?
