### ISSUE TITLE
Separate "Wand acquired" music from "Cottage" theme

### ISSUE THREAD

**Issue by wingheart** [FortWorthGameDev/HeartHome#93]
Right now there are two songs competing with each other when the Girl acquires the Wand. Could we try fading the Cottage music so the "Wand acquired" music can breathe a little?

**Comment by LanceBailey** [comment]
You're absolutely right we have a lot of audio competing with each other, I'll get that sorted with the transition to the ghost music too.

**Comment by LanceBailey** [comment]
Fixed with issue #28
